/// Flutter icons FaRegular
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FaRegular
///      fonts:
///       - asset: fonts/FaRegular.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FaRegular {
  FaRegular._();

  static const _kFontFam = 'FaRegular';

  static const IconData heart = const IconData(0xf004, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xf005, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xf007, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xf017, fontFamily: _kFontFam);
  static const IconData list_alt = const IconData(0xf022, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xf024, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xf02e, fontFamily: _kFontFam);
  static const IconData image = const IconData(0xf03e, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xf044, fontFamily: _kFontFam);
  static const IconData times_circle = const IconData(0xf057, fontFamily: _kFontFam);
  static const IconData check_circle = const IconData(0xf058, fontFamily: _kFontFam);
  static const IconData question_circle = const IconData(0xf059, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xf06e, fontFamily: _kFontFam);
  static const IconData eye_slash = const IconData(0xf070, fontFamily: _kFontFam);
  static const IconData calendar_alt = const IconData(0xf073, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xf075, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xf07b, fontFamily: _kFontFam);
  static const IconData folder_open = const IconData(0xf07c, fontFamily: _kFontFam);
  static const IconData chart_bar = const IconData(0xf080, fontFamily: _kFontFam);
  static const IconData comments = const IconData(0xf086, fontFamily: _kFontFam);
  static const IconData star_half = const IconData(0xf089, fontFamily: _kFontFam);
  static const IconData lemon = const IconData(0xf094, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xf09d, fontFamily: _kFontFam);
  static const IconData hdd = const IconData(0xf0a0, fontFamily: _kFontFam);
  static const IconData hand_point_right = const IconData(0xf0a4, fontFamily: _kFontFam);
  static const IconData hand_point_left = const IconData(0xf0a5, fontFamily: _kFontFam);
  static const IconData hand_point_up = const IconData(0xf0a6, fontFamily: _kFontFam);
  static const IconData hand_point_down = const IconData(0xf0a7, fontFamily: _kFontFam);
  static const IconData copy = const IconData(0xf0c5, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xf0c7, fontFamily: _kFontFam);
  static const IconData square = const IconData(0xf0c8, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xf0e0, fontFamily: _kFontFam);
  static const IconData lightbulb = const IconData(0xf0eb, fontFamily: _kFontFam);
  static const IconData bell = const IconData(0xf0f3, fontFamily: _kFontFam);
  static const IconData hospital = const IconData(0xf0f8, fontFamily: _kFontFam);
  static const IconData plus_square = const IconData(0xf0fe, fontFamily: _kFontFam);
  static const IconData circle = const IconData(0xf111, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xf118, fontFamily: _kFontFam);
  static const IconData frown = const IconData(0xf119, fontFamily: _kFontFam);
  static const IconData meh = const IconData(0xf11a, fontFamily: _kFontFam);
  static const IconData keyboard = const IconData(0xf11c, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xf133, fontFamily: _kFontFam);
  static const IconData play_circle = const IconData(0xf144, fontFamily: _kFontFam);
  static const IconData minus_square = const IconData(0xf146, fontFamily: _kFontFam);
  static const IconData check_square = const IconData(0xf14a, fontFamily: _kFontFam);
  static const IconData share_square = const IconData(0xf14d, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xf14e, fontFamily: _kFontFam);
  static const IconData caret_square_down = const IconData(0xf150, fontFamily: _kFontFam);
  static const IconData caret_square_up = const IconData(0xf151, fontFamily: _kFontFam);
  static const IconData caret_square_right = const IconData(0xf152, fontFamily: _kFontFam);
  static const IconData file = const IconData(0xf15b, fontFamily: _kFontFam);
  static const IconData file_alt = const IconData(0xf15c, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xf185, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xf186, fontFamily: _kFontFam);
  static const IconData caret_square_left = const IconData(0xf191, fontFamily: _kFontFam);
  static const IconData dot_circle = const IconData(0xf192, fontFamily: _kFontFam);
  static const IconData building = const IconData(0xf1ad, fontFamily: _kFontFam);
  static const IconData file_pdf = const IconData(0xf1c1, fontFamily: _kFontFam);
  static const IconData file_word = const IconData(0xf1c2, fontFamily: _kFontFam);
  static const IconData file_excel = const IconData(0xf1c3, fontFamily: _kFontFam);
  static const IconData file_powerpoint = const IconData(0xf1c4, fontFamily: _kFontFam);
  static const IconData file_image = const IconData(0xf1c5, fontFamily: _kFontFam);
  static const IconData file_archive = const IconData(0xf1c6, fontFamily: _kFontFam);
  static const IconData file_audio = const IconData(0xf1c7, fontFamily: _kFontFam);
  static const IconData file_video = const IconData(0xf1c8, fontFamily: _kFontFam);
  static const IconData file_code = const IconData(0xf1c9, fontFamily: _kFontFam);
  static const IconData life_ring = const IconData(0xf1cd, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xf1d8, fontFamily: _kFontFam);
  static const IconData futbol = const IconData(0xf1e3, fontFamily: _kFontFam);
  static const IconData newspaper = const IconData(0xf1ea, fontFamily: _kFontFam);
  static const IconData bell_slash = const IconData(0xf1f6, fontFamily: _kFontFam);
  static const IconData copyright = const IconData(0xf1f9, fontFamily: _kFontFam);
  static const IconData closed_captioning = const IconData(0xf20a, fontFamily: _kFontFam);
  static const IconData object_group = const IconData(0xf247, fontFamily: _kFontFam);
  static const IconData object_ungroup = const IconData(0xf248, fontFamily: _kFontFam);
  static const IconData sticky_note = const IconData(0xf249, fontFamily: _kFontFam);
  static const IconData clone = const IconData(0xf24d, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xf254, fontFamily: _kFontFam);
  static const IconData hand_rock = const IconData(0xf255, fontFamily: _kFontFam);
  static const IconData hand_paper = const IconData(0xf256, fontFamily: _kFontFam);
  static const IconData hand_scissors = const IconData(0xf257, fontFamily: _kFontFam);
  static const IconData hand_lizard = const IconData(0xf258, fontFamily: _kFontFam);
  static const IconData hand_spock = const IconData(0xf259, fontFamily: _kFontFam);
  static const IconData hand_pointer = const IconData(0xf25a, fontFamily: _kFontFam);
  static const IconData hand_peace = const IconData(0xf25b, fontFamily: _kFontFam);
  static const IconData registered = const IconData(0xf25d, fontFamily: _kFontFam);
  static const IconData calendar_plus = const IconData(0xf271, fontFamily: _kFontFam);
  static const IconData calendar_minus = const IconData(0xf272, fontFamily: _kFontFam);
  static const IconData calendar_times = const IconData(0xf273, fontFamily: _kFontFam);
  static const IconData calendar_check = const IconData(0xf274, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xf279, fontFamily: _kFontFam);
  static const IconData comment_alt = const IconData(0xf27a, fontFamily: _kFontFam);
  static const IconData pause_circle = const IconData(0xf28b, fontFamily: _kFontFam);
  static const IconData stop_circle = const IconData(0xf28d, fontFamily: _kFontFam);
  static const IconData handshake = const IconData(0xf2b5, fontFamily: _kFontFam);
  static const IconData envelope_open = const IconData(0xf2b6, fontFamily: _kFontFam);
  static const IconData address_book = const IconData(0xf2b9, fontFamily: _kFontFam);
  static const IconData address_card = const IconData(0xf2bb, fontFamily: _kFontFam);
  static const IconData user_circle = const IconData(0xf2bd, fontFamily: _kFontFam);
  static const IconData id_badge = const IconData(0xf2c1, fontFamily: _kFontFam);
  static const IconData id_card = const IconData(0xf2c2, fontFamily: _kFontFam);
  static const IconData window_maximize = const IconData(0xf2d0, fontFamily: _kFontFam);
  static const IconData window_minimize = const IconData(0xf2d1, fontFamily: _kFontFam);
  static const IconData window_restore = const IconData(0xf2d2, fontFamily: _kFontFam);
  static const IconData snowflake = const IconData(0xf2dc, fontFamily: _kFontFam);
  static const IconData trash_alt = const IconData(0xf2ed, fontFamily: _kFontFam);
  static const IconData images = const IconData(0xf302, fontFamily: _kFontFam);
  static const IconData clipboard = const IconData(0xf328, fontFamily: _kFontFam);
  static const IconData arrow_alt_circle_down = const IconData(0xf358, fontFamily: _kFontFam);
  static const IconData arrow_alt_circle_left = const IconData(0xf359, fontFamily: _kFontFam);
  static const IconData arrow_alt_circle_right = const IconData(0xf35a, fontFamily: _kFontFam);
  static const IconData arrow_alt_circle_up = const IconData(0xf35b, fontFamily: _kFontFam);
  static const IconData gem = const IconData(0xf3a5, fontFamily: _kFontFam);
  static const IconData money_bill_alt = const IconData(0xf3d1, fontFamily: _kFontFam);
  static const IconData window_close = const IconData(0xf410, fontFamily: _kFontFam);
  static const IconData comment_dots = const IconData(0xf4ad, fontFamily: _kFontFam);
  static const IconData smile_wink = const IconData(0xf4da, fontFamily: _kFontFam);
  static const IconData angry = const IconData(0xf556, fontFamily: _kFontFam);
  static const IconData dizzy = const IconData(0xf567, fontFamily: _kFontFam);
  static const IconData flushed = const IconData(0xf579, fontFamily: _kFontFam);
  static const IconData frown_open = const IconData(0xf57a, fontFamily: _kFontFam);
  static const IconData grimace = const IconData(0xf57f, fontFamily: _kFontFam);
  static const IconData grin = const IconData(0xf580, fontFamily: _kFontFam);
  static const IconData grin_alt = const IconData(0xf581, fontFamily: _kFontFam);
  static const IconData grin_beam = const IconData(0xf582, fontFamily: _kFontFam);
  static const IconData grin_beam_sweat = const IconData(0xf583, fontFamily: _kFontFam);
  static const IconData grin_hearts = const IconData(0xf584, fontFamily: _kFontFam);
  static const IconData grin_squint = const IconData(0xf585, fontFamily: _kFontFam);
  static const IconData grin_squint_tears = const IconData(0xf586, fontFamily: _kFontFam);
  static const IconData grin_stars = const IconData(0xf587, fontFamily: _kFontFam);
  static const IconData grin_tears = const IconData(0xf588, fontFamily: _kFontFam);
  static const IconData grin_tongue = const IconData(0xf589, fontFamily: _kFontFam);
  static const IconData grin_tongue_squint = const IconData(0xf58a, fontFamily: _kFontFam);
  static const IconData grin_tongue_wink = const IconData(0xf58b, fontFamily: _kFontFam);
  static const IconData grin_wink = const IconData(0xf58c, fontFamily: _kFontFam);
  static const IconData kiss = const IconData(0xf596, fontFamily: _kFontFam);
  static const IconData kiss_beam = const IconData(0xf597, fontFamily: _kFontFam);
  static const IconData kiss_wink_heart = const IconData(0xf598, fontFamily: _kFontFam);
  static const IconData laugh = const IconData(0xf599, fontFamily: _kFontFam);
  static const IconData laugh_beam = const IconData(0xf59a, fontFamily: _kFontFam);
  static const IconData laugh_squint = const IconData(0xf59b, fontFamily: _kFontFam);
  static const IconData laugh_wink = const IconData(0xf59c, fontFamily: _kFontFam);
  static const IconData meh_blank = const IconData(0xf5a4, fontFamily: _kFontFam);
  static const IconData meh_rolling_eyes = const IconData(0xf5a5, fontFamily: _kFontFam);
  static const IconData sad_cry = const IconData(0xf5b3, fontFamily: _kFontFam);
  static const IconData sad_tear = const IconData(0xf5b4, fontFamily: _kFontFam);
  static const IconData smile_beam = const IconData(0xf5b8, fontFamily: _kFontFam);
  static const IconData surprise = const IconData(0xf5c2, fontFamily: _kFontFam);
  static const IconData tired = const IconData(0xf5c8, fontFamily: _kFontFam);
}
